import { Entity, PrimaryGeneratedColumn, Column, ManyToOne } from "typeorm";
import { User } from "./User";

@Entity()
export class Todo {
  // Primary key: Unique identifier for each Todo item, auto-generated by the database.
  @PrimaryGeneratedColumn()
  id!: number;

  // Column: Title of the Todo item, stored as a string (varchar) with a maximum length of 255 characters.
  @Column({ type: "varchar", length: 255 })
  title!: string;

  // Column: Boolean flag indicating whether the Todo item is complete. Defaults to false.
  @Column({ type: "boolean", default: false })
  isComplete!: boolean;

  // Many-to-One Relationship: Associates each Todo item with a single User.
  // Eager loading: The related User entity is automatically loaded when a Todo item is fetched.
  // Cascade delete: Deleting a User will automatically delete all related Todo items.
  @ManyToOne(() => User, (user) => user.id, { eager: true, onDelete: "CASCADE" })
  user!: User;
}
