import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

@Entity()
export class User {
  // Primary key: Unique identifier for each User, auto-generated by the database.
  @PrimaryGeneratedColumn()
  id!: number;

  // Column: First name of the User, stored as a string (varchar) with a maximum length of 255 characters.
  @Column({ type: "varchar", length: 255 })
  firstName!: string;

  // Column: Last name of the User, stored as a string (varchar) with a maximum length of 255 characters.
  @Column({ type: "varchar", length: 255 })
  lastName!: string;

  // Column: Username of the User, stored as a unique string (varchar) with a maximum length of 255 characters.
  @Column({ type: "varchar", length: 255, unique: true })
  username!: string;

  // Column: Password of the User, stored as a string (varchar) with a maximum length of 255 characters.
  @Column({ type: "varchar", length: 255 })
  password!: string;
}
